title: NLP/ML/AI Conference Deadlines 
description: Countdowns to top NLP/ML/AI conference deadlines [credit to https://github.com/abhshkdz/ai-deadlines]
author: Danushka Bollegala

domain: "danushka.net/ai-deadlines"
baseurl: ""

twitter_username: bollegala
github_username: bollegala
github_repo: https://github.com/Bollegala/ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2
